### PR TITLE
Create lucaswashere.txt

### PR DESCRIPTION
**Pull request by clp93**
Just to  make sure everybody knows that lucas was here

### CODE REVIEW

**Comment by SkyrmionJ** [comment]
LGTM!!!!!

**Comment by mkli123** [comment]
Nah

**Comment by clp93** [comment]
+1

**Comment by clp93** [comment]
yo!

**Comment by clp93** [comment]
can someone please LGTM this crucial bit of code. It fixes all bugs and increases test coverage to 100%.

Thanks

**Pull request closed without merging**
